# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class MemberTuple(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        MemberTuple - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'member': 'Member',
            'member_user': 'MemberUser',
            'member_location': 'MemberLocation'
        }

        self.attribute_map = {
            'member': 'member',
            'member_user': 'member_user',
            'member_location': 'member_location'
        }

        self._member = None
        self._member_user = None
        self._member_location = None

    @property
    def member(self):
        """
        Gets the member of this MemberTuple.


        :return: The member of this MemberTuple.
        :rtype: Member
        """
        return self._member

    @member.setter
    def member(self, member):
        """
        Sets the member of this MemberTuple.


        :param member: The member of this MemberTuple.
        :type: Member
        """
        self._member = member

    @property
    def member_user(self):
        """
        Gets the member_user of this MemberTuple.


        :return: The member_user of this MemberTuple.
        :rtype: MemberUser
        """
        return self._member_user

    @member_user.setter
    def member_user(self, member_user):
        """
        Sets the member_user of this MemberTuple.


        :param member_user: The member_user of this MemberTuple.
        :type: MemberUser
        """
        self._member_user = member_user

    @property
    def member_location(self):
        """
        Gets the member_location of this MemberTuple.


        :return: The member_location of this MemberTuple.
        :rtype: MemberLocation
        """
        return self._member_location

    @member_location.setter
    def member_location(self, member_location):
        """
        Sets the member_location of this MemberTuple.


        :param member_location: The member_location of this MemberTuple.
        :type: MemberLocation
        """
        self._member_location = member_location

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

