# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class MemberCreateRequest(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        MemberCreateRequest - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'members': 'Member',
            'members_users': 'MemberUser',
            'members_locations': 'MemberLocation'
        }

        self.attribute_map = {
            'members': 'members',
            'members_users': 'members_users',
            'members_locations': 'members_locations'
        }

        self._members = None
        self._members_users = None
        self._members_locations = None

    @property
    def members(self):
        """
        Gets the members of this MemberCreateRequest.


        :return: The members of this MemberCreateRequest.
        :rtype: Member
        """
        return self._members

    @members.setter
    def members(self, members):
        """
        Sets the members of this MemberCreateRequest.


        :param members: The members of this MemberCreateRequest.
        :type: Member
        """
        self._members = members

    @property
    def members_users(self):
        """
        Gets the members_users of this MemberCreateRequest.


        :return: The members_users of this MemberCreateRequest.
        :rtype: MemberUser
        """
        return self._members_users

    @members_users.setter
    def members_users(self, members_users):
        """
        Sets the members_users of this MemberCreateRequest.


        :param members_users: The members_users of this MemberCreateRequest.
        :type: MemberUser
        """
        self._members_users = members_users

    @property
    def members_locations(self):
        """
        Gets the members_locations of this MemberCreateRequest.


        :return: The members_locations of this MemberCreateRequest.
        :rtype: MemberLocation
        """
        return self._members_locations

    @members_locations.setter
    def members_locations(self, members_locations):
        """
        Sets the members_locations of this MemberCreateRequest.


        :param members_locations: The members_locations of this MemberCreateRequest.
        :type: MemberLocation
        """
        self._members_locations = members_locations

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

